# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dictionary.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'dictionary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64ictionary.proto\x12\ndictionary\"*\n\tWordEntry\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x0f\n\x07meaning\x18\x02 \x01(\t\"\x1b\n\x0bWordRequest\x12\x0c\n\x04word\x18\x01 \x01(\t\"<\n\x0cWordResponse\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x0f\n\x07meaning\x18\x02 \x01(\t\x12\r\n\x05\x66ound\x18\x03 \x01(\x08\"*\n\x06Status\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x87\x01\n\x11\x44ictionaryService\x12\x34\n\x07\x41\x64\x64Word\x12\x15.dictionary.WordEntry\x1a\x12.dictionary.Status\x12<\n\x07GetWord\x12\x17.dictionary.WordRequest\x1a\x18.dictionary.WordResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dictionary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORDENTRY']._serialized_start=32
  _globals['_WORDENTRY']._serialized_end=74
  _globals['_WORDREQUEST']._serialized_start=76
  _globals['_WORDREQUEST']._serialized_end=103
  _globals['_WORDRESPONSE']._serialized_start=105
  _globals['_WORDRESPONSE']._serialized_end=165
  _globals['_STATUS']._serialized_start=167
  _globals['_STATUS']._serialized_end=209
  _globals['_DICTIONARYSERVICE']._serialized_start=212
  _globals['_DICTIONARYSERVICE']._serialized_end=347
# @@protoc_insertion_point(module_scope)
