# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DictionaryServiceStub(object):
    """Serviço de dicionário
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddWord = channel.unary_unary(
                '/service.DictionaryService/AddWord',
                request_serializer=service__pb2.AddWordRequest.SerializeToString,
                response_deserializer=service__pb2.AddWordResponse.FromString,
                _registered_method=True)
        self.ListWords = channel.unary_unary(
                '/service.DictionaryService/ListWords',
                request_serializer=service__pb2.ListWordsRequest.SerializeToString,
                response_deserializer=service__pb2.ListWordsResponse.FromString,
                _registered_method=True)


class DictionaryServiceServicer(object):
    """Serviço de dicionário
    """

    def AddWord(self, request, context):
        """Serviço para adicionar uma palavra
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWords(self, request, context):
        """Serviço para listar palavras
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DictionaryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddWord': grpc.unary_unary_rpc_method_handler(
                    servicer.AddWord,
                    request_deserializer=service__pb2.AddWordRequest.FromString,
                    response_serializer=service__pb2.AddWordResponse.SerializeToString,
            ),
            'ListWords': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWords,
                    request_deserializer=service__pb2.ListWordsRequest.FromString,
                    response_serializer=service__pb2.ListWordsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'service.DictionaryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('service.DictionaryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DictionaryService(object):
    """Serviço de dicionário
    """

    @staticmethod
    def AddWord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/service.DictionaryService/AddWord',
            service__pb2.AddWordRequest.SerializeToString,
            service__pb2.AddWordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/service.DictionaryService/ListWords',
            service__pb2.ListWordsRequest.SerializeToString,
            service__pb2.ListWordsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
