# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x07service\"2\n\x0e\x41\x64\x64WordRequest\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x12\n\ndefinition\x18\x02 \x01(\t\"\"\n\x0f\x41\x64\x64WordResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x12\n\x10ListWordsRequest\"\x14\n\x04Word\x12\x0c\n\x04word\x18\x01 \x01(\t\"1\n\x11ListWordsResponse\x12\x1c\n\x05words\x18\x01 \x03(\x0b\x32\r.service.Word2\x95\x01\n\x11\x44ictionaryService\x12<\n\x07\x41\x64\x64Word\x12\x17.service.AddWordRequest\x1a\x18.service.AddWordResponse\x12\x42\n\tListWords\x12\x19.service.ListWordsRequest\x1a\x1a.service.ListWordsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDWORDREQUEST']._serialized_start=26
  _globals['_ADDWORDREQUEST']._serialized_end=76
  _globals['_ADDWORDRESPONSE']._serialized_start=78
  _globals['_ADDWORDRESPONSE']._serialized_end=112
  _globals['_LISTWORDSREQUEST']._serialized_start=114
  _globals['_LISTWORDSREQUEST']._serialized_end=132
  _globals['_WORD']._serialized_start=134
  _globals['_WORD']._serialized_end=154
  _globals['_LISTWORDSRESPONSE']._serialized_start=156
  _globals['_LISTWORDSRESPONSE']._serialized_end=205
  _globals['_DICTIONARYSERVICE']._serialized_start=208
  _globals['_DICTIONARYSERVICE']._serialized_end=357
# @@protoc_insertion_point(module_scope)
